# import * from './Operation.gql'

query RecordsByMonth($month: String, $type: Operation, $accountsIds: [ID!], $categoriesIds: [ID!]) {
  records(month: $month, type: $type, accountsIds: $accountsIds, categoriesIds: $categoriesIds) {
    id
    date
    description
    amount
    type
    note
    tags
    user {
      id
      name
    }
    category {
      id
      description
      operation
    }
    account {
      id
      description
    }
  }
}